### ISSUE TITLE
Failed to load the http-status-codes package

### ISSUE THREAD

**Issue by RichardSummers** [josa42/atom-http-status-codes#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [http-status-codes](https://github.com/josa42/atom-http-status-codes) package, v1.0.4
### Stack Trace

Failed to load the http-status-codes package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/RichardSummers/.atom/packages/atom-http-status-codes-master/lib/http-status-codes-view.coffee:6:10)
    at Object.<anonymous> (/Users/RichardSummers/.atom/packages/atom-http-status-codes-master/lib/http-status-codes-view.coffee:60:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "wrap-guide",
      "welcome",
      "timecop",
      "spell-check",
      "metrics",
      "background-tips",
      "minimap",
      "open-in-browser",
      "preview-plus",
      "open-in-browser",
      "open-in-browser",
      "open-in-browser",
      "archive-view",
      "bracket-matcher",
      "git-diff",
      "go-to-line",
      "language-c",
      "language-clojure",
      "package-generator",
      "flex-tool-bar",
      "white-cursor",
      "deprecation-cop",
      "encoding-selector",
      "exception-reporting",
      "grammar-selector",
      "image-view",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-less",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-todo",
      "language-toml",
      "language-xml",
      "language-yaml",
      "link",
      "release-notes",
      "snippets",
      "styleguide",
      "symbols-view",
      "toolbar-iconshortcuts",
      "toolbar-iconshortcuts",
      "white-cursor",
      "toolbar-iconshortcuts",
      "terminal-status"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.10
autoclose-html, v0.18.0
filesize, v0.2.0
new-tab, v0.4.0
pigments, v0.9.2
run-in-browser, v0.1.3
tool-bar, v0.1.8
tool-bar-almighty, v0.0.3

# Dev
No dev packages
```

**Comment by josa42** [comment]
I cannot reproduce that. How did you install the package?

**Comment by RichardSummers** [comment]
Hi,
I downloaded your repo, then placed it in the atom packages directory, then restarted atom.

**Comment by RichardSummers** [comment]
Hi,
I downloaded your repo, then placed it in the atom packages directory, then restarted atom.

**Comment by josa42** [comment]
Ok than you need to install the dependencies yourself (`npm install` in the package directory).

Or the you do it the easy way and just install the package via atom. `apm install http-status-codes` in the shell or go to the settings.

See https://atom.io/docs/latest/using-atom-atom-packages
